# Generated by Django 2.2.4 on 2020-12-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201224_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='img',
            new_name='imgs',
        ),
    ]
