# Generated by Django 2.2.4 on 2020-12-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='event',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
    ]
